### ISSUE TITLE
[TP] More clarifications are required regarding signing consent when the trial is in particular statuses

### ISSUE THREAD

**Issue by klivit** [PharmaLedger-IMI/eco-iot-pmed-workspace#279]
<img width="1242" alt="Screenshot 2022-07-17 at 8 51 02 PM" src="https://user-images.githubusercontent.com/77613409/179419967-b4fb5a38-8551-4745-861f-6e063ad52c34.png">

**Comment by Mastaleru** [comment]
@Ana-ui, @klivit  what actions should be performed by the patient when the trial is "On Hold" or Cancelled?
Because I find useful that the patient still should have a possibility to withdraw/decline the consent while the status is "On Hold"

Can you make a table with all the actions that should be performed by the user on each section? consents, visits, questionnaire,

**Comment by Mastaleru** [comment]
fixed in https://github.com/PharmaLedger-IMI/trial-participant-ssapp/commit/c501158fecfdd8743490f5177ff1cbdc2f1542b0 and in https://github.com/PharmaLedger-IMI/trial-participant-ssapp/commit/dc2fd1662d1207c40f0295419fb837469a27c89c
