### ISSUE TITLE
Researcher app. Why data is not visible as soon as it is available.

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-iot-pmed-workspace#410]
![image](https://user-images.githubusercontent.com/1469129/186167991-7b482904-daba-4df2-a068-5e135c0312c9.png)

**Comment by Mastaleru** [comment]
@nliappas is this issue valid?

**Comment by nliappas** [comment]
researcher creates a study for a 2 month period
patient accepts immediately to share data
patient revokes the permission after 1 month

if the data is available asap, the researcher will see them. However, the patient revokes his permission after 1 month. The researcher could have stolen his data the first month. This is a privacy issue. That's why data has to be visible when study is completed.

**Comment by Mastaleru** [comment]
not an issue as Nikkos explained above
